# spring setting
spring:
      profiles:
        active: secrecy,dev
      servlet:
        multipart:
          max-request-size: 500MB
          max-file-size: 500MB
      jooq:
        sql-dialect: h2

# logging setting
logging:
  file: dms.log
  path: logs

# server setting
server:
  compression:
    enabled: true
    min-response-size: 1

