/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.dms.domain.dms.Dms;
import top.zbeboy.dms.domain.dms.Indexes;
import top.zbeboy.dms.domain.dms.Keys;
import top.zbeboy.dms.domain.dms.tables.records.NationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Nation extends TableImpl<NationRecord> {

    private static final long serialVersionUID = -1779353190;

    /**
     * The reference instance of <code>DMS.NATION</code>
     */
    public static final Nation NATION = new Nation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NationRecord> getRecordType() {
        return NationRecord.class;
    }

    /**
     * The column <code>DMS.NATION.NATION_ID</code>.
     */
    public final TableField<NationRecord, Integer> NATION_ID = createField("NATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>DMS.NATION.NATION_NAME</code>.
     */
    public final TableField<NationRecord, String> NATION_NAME = createField("NATION_NAME", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * Create a <code>DMS.NATION</code> table reference
     */
    public Nation() {
        this(DSL.name("NATION"), null);
    }

    /**
     * Create an aliased <code>DMS.NATION</code> table reference
     */
    public Nation(String alias) {
        this(DSL.name(alias), NATION);
    }

    /**
     * Create an aliased <code>DMS.NATION</code> table reference
     */
    public Nation(Name alias) {
        this(alias, NATION);
    }

    private Nation(Name alias, Table<NationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Nation(Name alias, Table<NationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dms.DMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<NationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_NATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<NationRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<NationRecord>> getKeys() {
        return Arrays.<UniqueKey<NationRecord>>asList(Keys.CONSTRAINT_8);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Nation as(String alias) {
        return new Nation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Nation as(Name alias) {
        return new Nation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Nation rename(String name) {
        return new Nation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Nation rename(Name name) {
        return new Nation(name, null);
    }
}
