/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.dms.domain.dms.Dms;
import top.zbeboy.dms.domain.dms.Indexes;
import top.zbeboy.dms.domain.dms.Keys;
import top.zbeboy.dms.domain.dms.tables.records.OrganizeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organize extends TableImpl<OrganizeRecord> {

    private static final long serialVersionUID = 539045608;

    /**
     * The reference instance of <code>DMS.ORGANIZE</code>
     */
    public static final Organize ORGANIZE = new Organize();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganizeRecord> getRecordType() {
        return OrganizeRecord.class;
    }

    /**
     * The column <code>DMS.ORGANIZE.ORGANIZE_ID</code>.
     */
    public final TableField<OrganizeRecord, Integer> ORGANIZE_ID = createField("ORGANIZE_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>DMS.ORGANIZE.ORGANIZE_NAME</code>.
     */
    public final TableField<OrganizeRecord, String> ORGANIZE_NAME = createField("ORGANIZE_NAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>DMS.ORGANIZE.GRADE_ID</code>.
     */
    public final TableField<OrganizeRecord, Integer> GRADE_ID = createField("GRADE_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>DMS.ORGANIZE</code> table reference
     */
    public Organize() {
        this(DSL.name("ORGANIZE"), null);
    }

    /**
     * Create an aliased <code>DMS.ORGANIZE</code> table reference
     */
    public Organize(String alias) {
        this(DSL.name(alias), ORGANIZE);
    }

    /**
     * Create an aliased <code>DMS.ORGANIZE</code> table reference
     */
    public Organize(Name alias) {
        this(alias, ORGANIZE);
    }

    private Organize(Name alias, Table<OrganizeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Organize(Name alias, Table<OrganizeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dms.DMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_7, Indexes.PRIMARY_KEY_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrganizeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORGANIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrganizeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_7;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrganizeRecord>> getKeys() {
        return Arrays.<UniqueKey<OrganizeRecord>>asList(Keys.CONSTRAINT_7);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrganizeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrganizeRecord, ?>>asList(Keys.CONSTRAINT_7D);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Organize as(String alias) {
        return new Organize(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Organize as(Name alias) {
        return new Organize(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Organize rename(String name) {
        return new Organize(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Organize rename(Name name) {
        return new Organize(name, null);
    }
}
