/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.dms.domain.dms.Dms;
import top.zbeboy.dms.domain.dms.Indexes;
import top.zbeboy.dms.domain.dms.Keys;
import top.zbeboy.dms.domain.dms.tables.records.PersistentLoginsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersistentLogins extends TableImpl<PersistentLoginsRecord> {

    private static final long serialVersionUID = 1025307057;

    /**
     * The reference instance of <code>DMS.PERSISTENT_LOGINS</code>
     */
    public static final PersistentLogins PERSISTENT_LOGINS = new PersistentLogins();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersistentLoginsRecord> getRecordType() {
        return PersistentLoginsRecord.class;
    }

    /**
     * The column <code>DMS.PERSISTENT_LOGINS.USERNAME</code>.
     */
    public final TableField<PersistentLoginsRecord, String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>DMS.PERSISTENT_LOGINS.SERIES</code>.
     */
    public final TableField<PersistentLoginsRecord, String> SERIES = createField("SERIES", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>DMS.PERSISTENT_LOGINS.TOKEN</code>.
     */
    public final TableField<PersistentLoginsRecord, String> TOKEN = createField("TOKEN", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>DMS.PERSISTENT_LOGINS.LAST_USED</code>.
     */
    public final TableField<PersistentLoginsRecord, Timestamp> LAST_USED = createField("LAST_USED", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>DMS.PERSISTENT_LOGINS</code> table reference
     */
    public PersistentLogins() {
        this(DSL.name("PERSISTENT_LOGINS"), null);
    }

    /**
     * Create an aliased <code>DMS.PERSISTENT_LOGINS</code> table reference
     */
    public PersistentLogins(String alias) {
        this(DSL.name(alias), PERSISTENT_LOGINS);
    }

    /**
     * Create an aliased <code>DMS.PERSISTENT_LOGINS</code> table reference
     */
    public PersistentLogins(Name alias) {
        this(alias, PERSISTENT_LOGINS);
    }

    private PersistentLogins(Name alias, Table<PersistentLoginsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PersistentLogins(Name alias, Table<PersistentLoginsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dms.DMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_A3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PersistentLoginsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_A3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PersistentLoginsRecord>> getKeys() {
        return Arrays.<UniqueKey<PersistentLoginsRecord>>asList(Keys.CONSTRAINT_A3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersistentLogins as(String alias) {
        return new PersistentLogins(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PersistentLogins as(Name alias) {
        return new PersistentLogins(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PersistentLogins rename(String name) {
        return new PersistentLogins(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PersistentLogins rename(Name name) {
        return new PersistentLogins(name, null);
    }
}
