/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.dms.domain.dms.Dms;
import top.zbeboy.dms.domain.dms.Indexes;
import top.zbeboy.dms.domain.dms.Keys;
import top.zbeboy.dms.domain.dms.tables.records.PoliticalLandscapeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoliticalLandscape extends TableImpl<PoliticalLandscapeRecord> {

    private static final long serialVersionUID = -865572997;

    /**
     * The reference instance of <code>DMS.POLITICAL_LANDSCAPE</code>
     */
    public static final PoliticalLandscape POLITICAL_LANDSCAPE = new PoliticalLandscape();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PoliticalLandscapeRecord> getRecordType() {
        return PoliticalLandscapeRecord.class;
    }

    /**
     * The column <code>DMS.POLITICAL_LANDSCAPE.POLITICAL_LANDSCAPE_ID</code>.
     */
    public final TableField<PoliticalLandscapeRecord, Integer> POLITICAL_LANDSCAPE_ID = createField("POLITICAL_LANDSCAPE_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>DMS.POLITICAL_LANDSCAPE.POLITICAL_LANDSCAPE_NAME</code>.
     */
    public final TableField<PoliticalLandscapeRecord, String> POLITICAL_LANDSCAPE_NAME = createField("POLITICAL_LANDSCAPE_NAME", org.jooq.impl.SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * Create a <code>DMS.POLITICAL_LANDSCAPE</code> table reference
     */
    public PoliticalLandscape() {
        this(DSL.name("POLITICAL_LANDSCAPE"), null);
    }

    /**
     * Create an aliased <code>DMS.POLITICAL_LANDSCAPE</code> table reference
     */
    public PoliticalLandscape(String alias) {
        this(DSL.name(alias), POLITICAL_LANDSCAPE);
    }

    /**
     * Create an aliased <code>DMS.POLITICAL_LANDSCAPE</code> table reference
     */
    public PoliticalLandscape(Name alias) {
        this(alias, POLITICAL_LANDSCAPE);
    }

    private PoliticalLandscape(Name alias, Table<PoliticalLandscapeRecord> aliased) {
        this(alias, aliased, null);
    }

    private PoliticalLandscape(Name alias, Table<PoliticalLandscapeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dms.DMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_4E);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PoliticalLandscapeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_POLITICAL_LANDSCAPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PoliticalLandscapeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4E;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PoliticalLandscapeRecord>> getKeys() {
        return Arrays.<UniqueKey<PoliticalLandscapeRecord>>asList(Keys.CONSTRAINT_4E);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoliticalLandscape as(String alias) {
        return new PoliticalLandscape(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PoliticalLandscape as(Name alias) {
        return new PoliticalLandscape(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PoliticalLandscape rename(String name) {
        return new PoliticalLandscape(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PoliticalLandscape rename(Name name) {
        return new PoliticalLandscape(name, null);
    }
}
