/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.dms.domain.dms.Dms;
import top.zbeboy.dms.domain.dms.Indexes;
import top.zbeboy.dms.domain.dms.Keys;
import top.zbeboy.dms.domain.dms.tables.records.ScienceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Science extends TableImpl<ScienceRecord> {

    private static final long serialVersionUID = 1550772227;

    /**
     * The reference instance of <code>DMS.SCIENCE</code>
     */
    public static final Science SCIENCE = new Science();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScienceRecord> getRecordType() {
        return ScienceRecord.class;
    }

    /**
     * The column <code>DMS.SCIENCE.SCIENCE_ID</code>.
     */
    public final TableField<ScienceRecord, Integer> SCIENCE_ID = createField("SCIENCE_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>DMS.SCIENCE.SCIENCE_NAME</code>.
     */
    public final TableField<ScienceRecord, String> SCIENCE_NAME = createField("SCIENCE_NAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>DMS.SCIENCE.DEPARTMENT_ID</code>.
     */
    public final TableField<ScienceRecord, Integer> DEPARTMENT_ID = createField("DEPARTMENT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>DMS.SCIENCE</code> table reference
     */
    public Science() {
        this(DSL.name("SCIENCE"), null);
    }

    /**
     * Create an aliased <code>DMS.SCIENCE</code> table reference
     */
    public Science(String alias) {
        this(DSL.name(alias), SCIENCE);
    }

    /**
     * Create an aliased <code>DMS.SCIENCE</code> table reference
     */
    public Science(Name alias) {
        this(alias, SCIENCE);
    }

    private Science(Name alias, Table<ScienceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Science(Name alias, Table<ScienceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dms.DMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONSTRAINT_INDEX_9, Indexes.PRIMARY_KEY_9D);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ScienceRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SCIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ScienceRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_9D;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ScienceRecord>> getKeys() {
        return Arrays.<UniqueKey<ScienceRecord>>asList(Keys.CONSTRAINT_9D);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ScienceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ScienceRecord, ?>>asList(Keys.CONSTRAINT_9D1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Science as(String alias) {
        return new Science(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Science as(Name alias) {
        return new Science(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Science rename(String name) {
        return new Science(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Science rename(Name name) {
        return new Science(name, null);
    }
}
