/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.dms.domain.dms.Dms;
import top.zbeboy.dms.domain.dms.Indexes;
import top.zbeboy.dms.domain.dms.Keys;
import top.zbeboy.dms.domain.dms.tables.records.SystemOperatorLogRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SystemOperatorLog extends TableImpl<SystemOperatorLogRecord> {

    private static final long serialVersionUID = 1821685710;

    /**
     * The reference instance of <code>DMS.SYSTEM_OPERATOR_LOG</code>
     */
    public static final SystemOperatorLog SYSTEM_OPERATOR_LOG = new SystemOperatorLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemOperatorLogRecord> getRecordType() {
        return SystemOperatorLogRecord.class;
    }

    /**
     * The column <code>DMS.SYSTEM_OPERATOR_LOG.LOG_ID</code>.
     */
    public final TableField<SystemOperatorLogRecord, String> LOG_ID = createField("LOG_ID", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>DMS.SYSTEM_OPERATOR_LOG.BEHAVIOR</code>.
     */
    public final TableField<SystemOperatorLogRecord, String> BEHAVIOR = createField("BEHAVIOR", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>DMS.SYSTEM_OPERATOR_LOG.OPERATING_TIME</code>.
     */
    public final TableField<SystemOperatorLogRecord, Timestamp> OPERATING_TIME = createField("OPERATING_TIME", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>DMS.SYSTEM_OPERATOR_LOG.USERNAME</code>.
     */
    public final TableField<SystemOperatorLogRecord, String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>DMS.SYSTEM_OPERATOR_LOG.IP_ADDRESS</code>.
     */
    public final TableField<SystemOperatorLogRecord, String> IP_ADDRESS = createField("IP_ADDRESS", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>DMS.SYSTEM_OPERATOR_LOG</code> table reference
     */
    public SystemOperatorLog() {
        this(DSL.name("SYSTEM_OPERATOR_LOG"), null);
    }

    /**
     * Create an aliased <code>DMS.SYSTEM_OPERATOR_LOG</code> table reference
     */
    public SystemOperatorLog(String alias) {
        this(DSL.name(alias), SYSTEM_OPERATOR_LOG);
    }

    /**
     * Create an aliased <code>DMS.SYSTEM_OPERATOR_LOG</code> table reference
     */
    public SystemOperatorLog(Name alias) {
        this(alias, SYSTEM_OPERATOR_LOG);
    }

    private SystemOperatorLog(Name alias, Table<SystemOperatorLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemOperatorLog(Name alias, Table<SystemOperatorLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dms.DMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_5);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SystemOperatorLogRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_5;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SystemOperatorLogRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemOperatorLogRecord>>asList(Keys.CONSTRAINT_5);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemOperatorLog as(String alias) {
        return new SystemOperatorLog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SystemOperatorLog as(Name alias) {
        return new SystemOperatorLog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemOperatorLog rename(String name) {
        return new SystemOperatorLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemOperatorLog rename(Name name) {
        return new SystemOperatorLog(name, null);
    }
}
