/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Department implements Serializable {

    private static final long serialVersionUID = -936712430;

    private Integer departmentId;
    private String  departmentName;
    private Integer collegeId;
    private Boolean departmentIsDel;

    public Department() {}

    public Department(Department value) {
        this.departmentId = value.departmentId;
        this.departmentName = value.departmentName;
        this.collegeId = value.collegeId;
        this.departmentIsDel = value.departmentIsDel;
    }

    public Department(
        Integer departmentId,
        String  departmentName,
        Integer collegeId,
        Boolean departmentIsDel
    ) {
        this.departmentId = departmentId;
        this.departmentName = departmentName;
        this.collegeId = collegeId;
        this.departmentIsDel = departmentIsDel;
    }

    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @NotNull
    @Size(max = 200)
    public String getDepartmentName() {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    @NotNull
    public Integer getCollegeId() {
        return this.collegeId;
    }

    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    public Boolean getDepartmentIsDel() {
        return this.departmentIsDel;
    }

    public void setDepartmentIsDel(Boolean departmentIsDel) {
        this.departmentIsDel = departmentIsDel;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Department (");

        sb.append(departmentId);
        sb.append(", ").append(departmentName);
        sb.append(", ").append(collegeId);
        sb.append(", ").append(departmentIsDel);

        sb.append(")");
        return sb.toString();
    }
}
