/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Diploma implements Serializable {

    private static final long serialVersionUID = 755272610;

    private Integer diplomaId;
    private String  studentNumber;
    private String  year;
    private Integer term;
    private String  diplomaName;

    public Diploma() {}

    public Diploma(Diploma value) {
        this.diplomaId = value.diplomaId;
        this.studentNumber = value.studentNumber;
        this.year = value.year;
        this.term = value.term;
        this.diplomaName = value.diplomaName;
    }

    public Diploma(
        Integer diplomaId,
        String  studentNumber,
        String  year,
        Integer term,
        String  diplomaName
    ) {
        this.diplomaId = diplomaId;
        this.studentNumber = studentNumber;
        this.year = year;
        this.term = term;
        this.diplomaName = diplomaName;
    }

    public Integer getDiplomaId() {
        return this.diplomaId;
    }

    public void setDiplomaId(Integer diplomaId) {
        this.diplomaId = diplomaId;
    }

    @NotNull
    @Size(max = 20)
    public String getStudentNumber() {
        return this.studentNumber;
    }

    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
    }

    @NotNull
    @Size(max = 5)
    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    @NotNull
    public Integer getTerm() {
        return this.term;
    }

    public void setTerm(Integer term) {
        this.term = term;
    }

    @NotNull
    @Size(max = 500)
    public String getDiplomaName() {
        return this.diplomaName;
    }

    public void setDiplomaName(String diplomaName) {
        this.diplomaName = diplomaName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Diploma (");

        sb.append(diplomaId);
        sb.append(", ").append(studentNumber);
        sb.append(", ").append(year);
        sb.append(", ").append(term);
        sb.append(", ").append(diplomaName);

        sb.append(")");
        return sb.toString();
    }
}
