/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Evaluate implements Serializable {

    private static final long serialVersionUID = 650731360;

    private String evaluateId;
    private String evaluateContent;

    public Evaluate() {}

    public Evaluate(Evaluate value) {
        this.evaluateId = value.evaluateId;
        this.evaluateContent = value.evaluateContent;
    }

    public Evaluate(
        String evaluateId,
        String evaluateContent
    ) {
        this.evaluateId = evaluateId;
        this.evaluateContent = evaluateContent;
    }

    @NotNull
    @Size(max = 64)
    public String getEvaluateId() {
        return this.evaluateId;
    }

    public void setEvaluateId(String evaluateId) {
        this.evaluateId = evaluateId;
    }

    @Size(max = 200)
    public String getEvaluateContent() {
        return this.evaluateContent;
    }

    public void setEvaluateContent(String evaluateContent) {
        this.evaluateContent = evaluateContent;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Evaluate (");

        sb.append(evaluateId);
        sb.append(", ").append(evaluateContent);

        sb.append(")");
        return sb.toString();
    }
}
