/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QualityApply implements Serializable {

    private static final long serialVersionUID = 1950446717;

    private String    qualityApplyId;
    private Integer   studentId;
    private String    applyContent;
    private Integer   applyState;
    private Timestamp applyDate;

    public QualityApply() {}

    public QualityApply(QualityApply value) {
        this.qualityApplyId = value.qualityApplyId;
        this.studentId = value.studentId;
        this.applyContent = value.applyContent;
        this.applyState = value.applyState;
        this.applyDate = value.applyDate;
    }

    public QualityApply(
        String    qualityApplyId,
        Integer   studentId,
        String    applyContent,
        Integer   applyState,
        Timestamp applyDate
    ) {
        this.qualityApplyId = qualityApplyId;
        this.studentId = studentId;
        this.applyContent = applyContent;
        this.applyState = applyState;
        this.applyDate = applyDate;
    }

    @NotNull
    @Size(max = 64)
    public String getQualityApplyId() {
        return this.qualityApplyId;
    }

    public void setQualityApplyId(String qualityApplyId) {
        this.qualityApplyId = qualityApplyId;
    }

    @NotNull
    public Integer getStudentId() {
        return this.studentId;
    }

    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    @Size(max = 100)
    public String getApplyContent() {
        return this.applyContent;
    }

    public void setApplyContent(String applyContent) {
        this.applyContent = applyContent;
    }

    public Integer getApplyState() {
        return this.applyState;
    }

    public void setApplyState(Integer applyState) {
        this.applyState = applyState;
    }

    @NotNull
    public Timestamp getApplyDate() {
        return this.applyDate;
    }

    public void setApplyDate(Timestamp applyDate) {
        this.applyDate = applyDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QualityApply (");

        sb.append(qualityApplyId);
        sb.append(", ").append(studentId);
        sb.append(", ").append(applyContent);
        sb.append(", ").append(applyState);
        sb.append(", ").append(applyDate);

        sb.append(")");
        return sb.toString();
    }
}
