/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Science implements Serializable {

    private static final long serialVersionUID = -328355447;

    private Integer scienceId;
    private String  scienceName;
    private Integer departmentId;
    private Boolean scienceIsDel;

    public Science() {}

    public Science(Science value) {
        this.scienceId = value.scienceId;
        this.scienceName = value.scienceName;
        this.departmentId = value.departmentId;
        this.scienceIsDel = value.scienceIsDel;
    }

    public Science(
        Integer scienceId,
        String  scienceName,
        Integer departmentId,
        Boolean scienceIsDel
    ) {
        this.scienceId = scienceId;
        this.scienceName = scienceName;
        this.departmentId = departmentId;
        this.scienceIsDel = scienceIsDel;
    }

    public Integer getScienceId() {
        return this.scienceId;
    }

    public void setScienceId(Integer scienceId) {
        this.scienceId = scienceId;
    }

    @NotNull
    @Size(max = 200)
    public String getScienceName() {
        return this.scienceName;
    }

    public void setScienceName(String scienceName) {
        this.scienceName = scienceName;
    }

    @NotNull
    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public Boolean getScienceIsDel() {
        return this.scienceIsDel;
    }

    public void setScienceIsDel(Boolean scienceIsDel) {
        this.scienceIsDel = scienceIsDel;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Science (");

        sb.append(scienceId);
        sb.append(", ").append(scienceName);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(scienceIsDel);

        sb.append(")");
        return sb.toString();
    }
}
