/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Staff implements Serializable {

    private static final long serialVersionUID = -6152329;

    private Integer staffId;
    private String  staffNumber;
    private String  sex;
    private Integer politicalLandscapeId;
    private Integer departmentId;
    private String  username;

    public Staff() {}

    public Staff(Staff value) {
        this.staffId = value.staffId;
        this.staffNumber = value.staffNumber;
        this.sex = value.sex;
        this.politicalLandscapeId = value.politicalLandscapeId;
        this.departmentId = value.departmentId;
        this.username = value.username;
    }

    public Staff(
        Integer staffId,
        String  staffNumber,
        String  sex,
        Integer politicalLandscapeId,
        Integer departmentId,
        String  username
    ) {
        this.staffId = staffId;
        this.staffNumber = staffNumber;
        this.sex = sex;
        this.politicalLandscapeId = politicalLandscapeId;
        this.departmentId = departmentId;
        this.username = username;
    }

    public Integer getStaffId() {
        return this.staffId;
    }

    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    @NotNull
    @Size(max = 20)
    public String getStaffNumber() {
        return this.staffNumber;
    }

    public void setStaffNumber(String staffNumber) {
        this.staffNumber = staffNumber;
    }

    @Size(max = 2)
    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getPoliticalLandscapeId() {
        return this.politicalLandscapeId;
    }

    public void setPoliticalLandscapeId(Integer politicalLandscapeId) {
        this.politicalLandscapeId = politicalLandscapeId;
    }

    @NotNull
    public Integer getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Staff (");

        sb.append(staffId);
        sb.append(", ").append(staffNumber);
        sb.append(", ").append(sex);
        sb.append(", ").append(politicalLandscapeId);
        sb.append(", ").append(departmentId);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
