/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = -612637910;

    private String  username;
    private String  password;
    private Boolean enabled;
    private Boolean accountNonExpired;
    private Boolean credentialsNonExpired;
    private Boolean accountNonLocked;
    private Integer usersTypeId;
    private String  realName;
    private String  avatar;
    private Date    joinDate;

    public Users() {}

    public Users(Users value) {
        this.username = value.username;
        this.password = value.password;
        this.enabled = value.enabled;
        this.accountNonExpired = value.accountNonExpired;
        this.credentialsNonExpired = value.credentialsNonExpired;
        this.accountNonLocked = value.accountNonLocked;
        this.usersTypeId = value.usersTypeId;
        this.realName = value.realName;
        this.avatar = value.avatar;
        this.joinDate = value.joinDate;
    }

    public Users(
        String  username,
        String  password,
        Boolean enabled,
        Boolean accountNonExpired,
        Boolean credentialsNonExpired,
        Boolean accountNonLocked,
        Integer usersTypeId,
        String  realName,
        String  avatar,
        Date    joinDate
    ) {
        this.username = username;
        this.password = password;
        this.enabled = enabled;
        this.accountNonExpired = accountNonExpired;
        this.credentialsNonExpired = credentialsNonExpired;
        this.accountNonLocked = accountNonLocked;
        this.usersTypeId = usersTypeId;
        this.realName = realName;
        this.avatar = avatar;
        this.joinDate = joinDate;
    }

    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @NotNull
    @Size(max = 300)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @NotNull
    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @NotNull
    public Boolean getAccountNonExpired() {
        return this.accountNonExpired;
    }

    public void setAccountNonExpired(Boolean accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }

    @NotNull
    public Boolean getCredentialsNonExpired() {
        return this.credentialsNonExpired;
    }

    public void setCredentialsNonExpired(Boolean credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }

    @NotNull
    public Boolean getAccountNonLocked() {
        return this.accountNonLocked;
    }

    public void setAccountNonLocked(Boolean accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }

    @NotNull
    public Integer getUsersTypeId() {
        return this.usersTypeId;
    }

    public void setUsersTypeId(Integer usersTypeId) {
        this.usersTypeId = usersTypeId;
    }

    @Size(max = 30)
    public String getRealName() {
        return this.realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    @Size(max = 64)
    public String getAvatar() {
        return this.avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public Date getJoinDate() {
        return this.joinDate;
    }

    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(enabled);
        sb.append(", ").append(accountNonExpired);
        sb.append(", ").append(credentialsNonExpired);
        sb.append(", ").append(accountNonLocked);
        sb.append(", ").append(usersTypeId);
        sb.append(", ").append(realName);
        sb.append(", ").append(avatar);
        sb.append(", ").append(joinDate);

        sb.append(")");
        return sb.toString();
    }
}
