/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wining implements Serializable {

    private static final long serialVersionUID = 1523780134;

    private Integer winingId;
    private Integer creditId;
    private String  winingContent;
    private Double  winingScore;

    public Wining() {}

    public Wining(Wining value) {
        this.winingId = value.winingId;
        this.creditId = value.creditId;
        this.winingContent = value.winingContent;
        this.winingScore = value.winingScore;
    }

    public Wining(
        Integer winingId,
        Integer creditId,
        String  winingContent,
        Double  winingScore
    ) {
        this.winingId = winingId;
        this.creditId = creditId;
        this.winingContent = winingContent;
        this.winingScore = winingScore;
    }

    public Integer getWiningId() {
        return this.winingId;
    }

    public void setWiningId(Integer winingId) {
        this.winingId = winingId;
    }

    @NotNull
    public Integer getCreditId() {
        return this.creditId;
    }

    public void setCreditId(Integer creditId) {
        this.creditId = creditId;
    }

    @NotNull
    @Size(max = 500)
    public String getWiningContent() {
        return this.winingContent;
    }

    public void setWiningContent(String winingContent) {
        this.winingContent = winingContent;
    }

    public Double getWiningScore() {
        return this.winingScore;
    }

    public void setWiningScore(Double winingScore) {
        this.winingScore = winingScore;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Wining (");

        sb.append(winingId);
        sb.append(", ").append(creditId);
        sb.append(", ").append(winingContent);
        sb.append(", ").append(winingScore);

        sb.append(")");
        return sb.toString();
    }
}
