/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wining implements Serializable {

    private static final long serialVersionUID = 1837299486;

    private Integer winingId;
    private String  studentNumber;
    private String  year;
    private Integer term;
    private String  winingContent;
    private Double  winingScore;

    public Wining() {}

    public Wining(Wining value) {
        this.winingId = value.winingId;
        this.studentNumber = value.studentNumber;
        this.year = value.year;
        this.term = value.term;
        this.winingContent = value.winingContent;
        this.winingScore = value.winingScore;
    }

    public Wining(
        Integer winingId,
        String  studentNumber,
        String  year,
        Integer term,
        String  winingContent,
        Double  winingScore
    ) {
        this.winingId = winingId;
        this.studentNumber = studentNumber;
        this.year = year;
        this.term = term;
        this.winingContent = winingContent;
        this.winingScore = winingScore;
    }

    public Integer getWiningId() {
        return this.winingId;
    }

    public void setWiningId(Integer winingId) {
        this.winingId = winingId;
    }

    @NotNull
    @Size(max = 20)
    public String getStudentNumber() {
        return this.studentNumber;
    }

    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
    }

    @NotNull
    @Size(max = 5)
    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    @NotNull
    public Integer getTerm() {
        return this.term;
    }

    public void setTerm(Integer term) {
        this.term = term;
    }

    @NotNull
    @Size(max = 500)
    public String getWiningContent() {
        return this.winingContent;
    }

    public void setWiningContent(String winingContent) {
        this.winingContent = winingContent;
    }

    public Double getWiningScore() {
        return this.winingScore;
    }

    public void setWiningScore(Double winingScore) {
        this.winingScore = winingScore;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Wining (");

        sb.append(winingId);
        sb.append(", ").append(studentNumber);
        sb.append(", ").append(year);
        sb.append(", ").append(term);
        sb.append(", ").append(winingContent);
        sb.append(", ").append(winingScore);

        sb.append(")");
        return sb.toString();
    }
}
