/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms;


import javax.annotation.Generated;

import top.zbeboy.dms.domain.dms.tables.Authorities;
import top.zbeboy.dms.domain.dms.tables.College;
import top.zbeboy.dms.domain.dms.tables.Credit;
import top.zbeboy.dms.domain.dms.tables.Department;
import top.zbeboy.dms.domain.dms.tables.Diploma;
import top.zbeboy.dms.domain.dms.tables.Files;
import top.zbeboy.dms.domain.dms.tables.Grade;
import top.zbeboy.dms.domain.dms.tables.Organize;
import top.zbeboy.dms.domain.dms.tables.PersistentLogins;
import top.zbeboy.dms.domain.dms.tables.PoliticalLandscape;
import top.zbeboy.dms.domain.dms.tables.QualityApply;
import top.zbeboy.dms.domain.dms.tables.QualityRelease;
import top.zbeboy.dms.domain.dms.tables.School;
import top.zbeboy.dms.domain.dms.tables.Science;
import top.zbeboy.dms.domain.dms.tables.Staff;
import top.zbeboy.dms.domain.dms.tables.Student;
import top.zbeboy.dms.domain.dms.tables.SystemConfigure;
import top.zbeboy.dms.domain.dms.tables.SystemOperatorLog;
import top.zbeboy.dms.domain.dms.tables.Users;
import top.zbeboy.dms.domain.dms.tables.UsersType;
import top.zbeboy.dms.domain.dms.tables.Wining;


/**
 * Convenience access to all tables in DMS
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DMS.AUTHORITIES</code>.
     */
    public static final Authorities AUTHORITIES = top.zbeboy.dms.domain.dms.tables.Authorities.AUTHORITIES;

    /**
     * The table <code>DMS.COLLEGE</code>.
     */
    public static final College COLLEGE = top.zbeboy.dms.domain.dms.tables.College.COLLEGE;

    /**
     * The table <code>DMS.CREDIT</code>.
     */
    public static final Credit CREDIT = top.zbeboy.dms.domain.dms.tables.Credit.CREDIT;

    /**
     * The table <code>DMS.DEPARTMENT</code>.
     */
    public static final Department DEPARTMENT = top.zbeboy.dms.domain.dms.tables.Department.DEPARTMENT;

    /**
     * The table <code>DMS.DIPLOMA</code>.
     */
    public static final Diploma DIPLOMA = top.zbeboy.dms.domain.dms.tables.Diploma.DIPLOMA;

    /**
     * The table <code>DMS.FILES</code>.
     */
    public static final Files FILES = top.zbeboy.dms.domain.dms.tables.Files.FILES;

    /**
     * The table <code>DMS.GRADE</code>.
     */
    public static final Grade GRADE = top.zbeboy.dms.domain.dms.tables.Grade.GRADE;

    /**
     * The table <code>DMS.ORGANIZE</code>.
     */
    public static final Organize ORGANIZE = top.zbeboy.dms.domain.dms.tables.Organize.ORGANIZE;

    /**
     * The table <code>DMS.PERSISTENT_LOGINS</code>.
     */
    public static final PersistentLogins PERSISTENT_LOGINS = top.zbeboy.dms.domain.dms.tables.PersistentLogins.PERSISTENT_LOGINS;

    /**
     * The table <code>DMS.POLITICAL_LANDSCAPE</code>.
     */
    public static final PoliticalLandscape POLITICAL_LANDSCAPE = top.zbeboy.dms.domain.dms.tables.PoliticalLandscape.POLITICAL_LANDSCAPE;

    /**
     * The table <code>DMS.QUALITY_APPLY</code>.
     */
    public static final QualityApply QUALITY_APPLY = top.zbeboy.dms.domain.dms.tables.QualityApply.QUALITY_APPLY;

    /**
     * The table <code>DMS.QUALITY_RELEASE</code>.
     */
    public static final QualityRelease QUALITY_RELEASE = top.zbeboy.dms.domain.dms.tables.QualityRelease.QUALITY_RELEASE;

    /**
     * The table <code>DMS.SCHOOL</code>.
     */
    public static final School SCHOOL = top.zbeboy.dms.domain.dms.tables.School.SCHOOL;

    /**
     * The table <code>DMS.SCIENCE</code>.
     */
    public static final Science SCIENCE = top.zbeboy.dms.domain.dms.tables.Science.SCIENCE;

    /**
     * The table <code>DMS.STAFF</code>.
     */
    public static final Staff STAFF = top.zbeboy.dms.domain.dms.tables.Staff.STAFF;

    /**
     * The table <code>DMS.STUDENT</code>.
     */
    public static final Student STUDENT = top.zbeboy.dms.domain.dms.tables.Student.STUDENT;

    /**
     * The table <code>DMS.SYSTEM_CONFIGURE</code>.
     */
    public static final SystemConfigure SYSTEM_CONFIGURE = top.zbeboy.dms.domain.dms.tables.SystemConfigure.SYSTEM_CONFIGURE;

    /**
     * The table <code>DMS.SYSTEM_OPERATOR_LOG</code>.
     */
    public static final SystemOperatorLog SYSTEM_OPERATOR_LOG = top.zbeboy.dms.domain.dms.tables.SystemOperatorLog.SYSTEM_OPERATOR_LOG;

    /**
     * The table <code>DMS.USERS</code>.
     */
    public static final Users USERS = top.zbeboy.dms.domain.dms.tables.Users.USERS;

    /**
     * The table <code>DMS.USERS_TYPE</code>.
     */
    public static final UsersType USERS_TYPE = top.zbeboy.dms.domain.dms.tables.UsersType.USERS_TYPE;

    /**
     * The table <code>DMS.WINING</code>.
     */
    public static final Wining WINING = top.zbeboy.dms.domain.dms.tables.Wining.WINING;
}
