/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.Evaluate;
import top.zbeboy.dms.domain.dms.tables.records.EvaluateRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class EvaluateDao extends DAOImpl<EvaluateRecord, top.zbeboy.dms.domain.dms.tables.pojos.Evaluate, String> {

    /**
     * Create a new EvaluateDao without any configuration
     */
    public EvaluateDao() {
        super(Evaluate.EVALUATE, top.zbeboy.dms.domain.dms.tables.pojos.Evaluate.class);
    }

    /**
     * Create a new EvaluateDao with an attached configuration
     */
    @Autowired
    public EvaluateDao(Configuration configuration) {
        super(Evaluate.EVALUATE, top.zbeboy.dms.domain.dms.tables.pojos.Evaluate.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.dms.domain.dms.tables.pojos.Evaluate object) {
        return object.getEvaluateId();
    }

    /**
     * Fetch records that have <code>EVALUATE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Evaluate> fetchByEvaluateId(String... values) {
        return fetch(Evaluate.EVALUATE.EVALUATE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>EVALUATE_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.Evaluate fetchOneByEvaluateId(String value) {
        return fetchOne(Evaluate.EVALUATE.EVALUATE_ID, value);
    }

    /**
     * Fetch records that have <code>EVALUATE_CONTENT IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Evaluate> fetchByEvaluateContent(String... values) {
        return fetch(Evaluate.EVALUATE.EVALUATE_CONTENT, values);
    }
}
