/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.Files;
import top.zbeboy.dms.domain.dms.tables.records.FilesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class FilesDao extends DAOImpl<FilesRecord, top.zbeboy.dms.domain.dms.tables.pojos.Files, String> {

    /**
     * Create a new FilesDao without any configuration
     */
    public FilesDao() {
        super(Files.FILES, top.zbeboy.dms.domain.dms.tables.pojos.Files.class);
    }

    /**
     * Create a new FilesDao with an attached configuration
     */
    @Autowired
    public FilesDao(Configuration configuration) {
        super(Files.FILES, top.zbeboy.dms.domain.dms.tables.pojos.Files.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.dms.domain.dms.tables.pojos.Files object) {
        return object.getFileId();
    }

    /**
     * Fetch records that have <code>FILE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Files> fetchByFileId(String... values) {
        return fetch(Files.FILES.FILE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>FILE_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.Files fetchOneByFileId(String value) {
        return fetchOne(Files.FILES.FILE_ID, value);
    }

    /**
     * Fetch records that have <code>FILE_SIZE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Files> fetchByFileSize(Long... values) {
        return fetch(Files.FILES.FILE_SIZE, values);
    }

    /**
     * Fetch records that have <code>CONTENT_TYPE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Files> fetchByContentType(String... values) {
        return fetch(Files.FILES.CONTENT_TYPE, values);
    }

    /**
     * Fetch records that have <code>ORIGINAL_FILE_NAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Files> fetchByOriginalFileName(String... values) {
        return fetch(Files.FILES.ORIGINAL_FILE_NAME, values);
    }

    /**
     * Fetch records that have <code>NEW_NAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Files> fetchByNewName(String... values) {
        return fetch(Files.FILES.NEW_NAME, values);
    }

    /**
     * Fetch records that have <code>RELATIVE_PATH IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Files> fetchByRelativePath(String... values) {
        return fetch(Files.FILES.RELATIVE_PATH, values);
    }

    /**
     * Fetch records that have <code>EXT IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Files> fetchByExt(String... values) {
        return fetch(Files.FILES.EXT, values);
    }
}
