/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.Grade;
import top.zbeboy.dms.domain.dms.tables.records.GradeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class GradeDao extends DAOImpl<GradeRecord, top.zbeboy.dms.domain.dms.tables.pojos.Grade, Integer> {

    /**
     * Create a new GradeDao without any configuration
     */
    public GradeDao() {
        super(Grade.GRADE, top.zbeboy.dms.domain.dms.tables.pojos.Grade.class);
    }

    /**
     * Create a new GradeDao with an attached configuration
     */
    @Autowired
    public GradeDao(Configuration configuration) {
        super(Grade.GRADE, top.zbeboy.dms.domain.dms.tables.pojos.Grade.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(top.zbeboy.dms.domain.dms.tables.pojos.Grade object) {
        return object.getGradeId();
    }

    /**
     * Fetch records that have <code>GRADE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Grade> fetchByGradeId(Integer... values) {
        return fetch(Grade.GRADE.GRADE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>GRADE_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.Grade fetchOneByGradeId(Integer value) {
        return fetchOne(Grade.GRADE.GRADE_ID, value);
    }

    /**
     * Fetch records that have <code>GRADE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Grade> fetchByGrade(String... values) {
        return fetch(Grade.GRADE.GRADE_, values);
    }

    /**
     * Fetch records that have <code>SCIENCE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Grade> fetchByScienceId(Integer... values) {
        return fetch(Grade.GRADE.SCIENCE_ID, values);
    }
}
