/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.Organize;
import top.zbeboy.dms.domain.dms.tables.records.OrganizeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class OrganizeDao extends DAOImpl<OrganizeRecord, top.zbeboy.dms.domain.dms.tables.pojos.Organize, Integer> {

    /**
     * Create a new OrganizeDao without any configuration
     */
    public OrganizeDao() {
        super(Organize.ORGANIZE, top.zbeboy.dms.domain.dms.tables.pojos.Organize.class);
    }

    /**
     * Create a new OrganizeDao with an attached configuration
     */
    @Autowired
    public OrganizeDao(Configuration configuration) {
        super(Organize.ORGANIZE, top.zbeboy.dms.domain.dms.tables.pojos.Organize.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(top.zbeboy.dms.domain.dms.tables.pojos.Organize object) {
        return object.getOrganizeId();
    }

    /**
     * Fetch records that have <code>ORGANIZE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Organize> fetchByOrganizeId(Integer... values) {
        return fetch(Organize.ORGANIZE.ORGANIZE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>ORGANIZE_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.Organize fetchOneByOrganizeId(Integer value) {
        return fetchOne(Organize.ORGANIZE.ORGANIZE_ID, value);
    }

    /**
     * Fetch records that have <code>ORGANIZE_NAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Organize> fetchByOrganizeName(String... values) {
        return fetch(Organize.ORGANIZE.ORGANIZE_NAME, values);
    }

    /**
     * Fetch records that have <code>GRADE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Organize> fetchByGradeId(Integer... values) {
        return fetch(Organize.ORGANIZE.GRADE_ID, values);
    }
}
