/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.PersistentLogins;
import top.zbeboy.dms.domain.dms.tables.records.PersistentLoginsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PersistentLoginsDao extends DAOImpl<PersistentLoginsRecord, top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins, String> {

    /**
     * Create a new PersistentLoginsDao without any configuration
     */
    public PersistentLoginsDao() {
        super(PersistentLogins.PERSISTENT_LOGINS, top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins.class);
    }

    /**
     * Create a new PersistentLoginsDao with an attached configuration
     */
    @Autowired
    public PersistentLoginsDao(Configuration configuration) {
        super(PersistentLogins.PERSISTENT_LOGINS, top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins object) {
        return object.getSeries();
    }

    /**
     * Fetch records that have <code>USERNAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins> fetchByUsername(String... values) {
        return fetch(PersistentLogins.PERSISTENT_LOGINS.USERNAME, values);
    }

    /**
     * Fetch records that have <code>SERIES IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins> fetchBySeries(String... values) {
        return fetch(PersistentLogins.PERSISTENT_LOGINS.SERIES, values);
    }

    /**
     * Fetch a unique record that has <code>SERIES = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins fetchOneBySeries(String value) {
        return fetchOne(PersistentLogins.PERSISTENT_LOGINS.SERIES, value);
    }

    /**
     * Fetch records that have <code>TOKEN IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins> fetchByToken(String... values) {
        return fetch(PersistentLogins.PERSISTENT_LOGINS.TOKEN, values);
    }

    /**
     * Fetch records that have <code>LAST_USED IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.PersistentLogins> fetchByLastUsed(Timestamp... values) {
        return fetch(PersistentLogins.PERSISTENT_LOGINS.LAST_USED, values);
    }
}
