/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.PoliticalLandscape;
import top.zbeboy.dms.domain.dms.tables.records.PoliticalLandscapeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PoliticalLandscapeDao extends DAOImpl<PoliticalLandscapeRecord, top.zbeboy.dms.domain.dms.tables.pojos.PoliticalLandscape, Integer> {

    /**
     * Create a new PoliticalLandscapeDao without any configuration
     */
    public PoliticalLandscapeDao() {
        super(PoliticalLandscape.POLITICAL_LANDSCAPE, top.zbeboy.dms.domain.dms.tables.pojos.PoliticalLandscape.class);
    }

    /**
     * Create a new PoliticalLandscapeDao with an attached configuration
     */
    @Autowired
    public PoliticalLandscapeDao(Configuration configuration) {
        super(PoliticalLandscape.POLITICAL_LANDSCAPE, top.zbeboy.dms.domain.dms.tables.pojos.PoliticalLandscape.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(top.zbeboy.dms.domain.dms.tables.pojos.PoliticalLandscape object) {
        return object.getPoliticalLandscapeId();
    }

    /**
     * Fetch records that have <code>POLITICAL_LANDSCAPE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.PoliticalLandscape> fetchByPoliticalLandscapeId(Integer... values) {
        return fetch(PoliticalLandscape.POLITICAL_LANDSCAPE.POLITICAL_LANDSCAPE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>POLITICAL_LANDSCAPE_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.PoliticalLandscape fetchOneByPoliticalLandscapeId(Integer value) {
        return fetchOne(PoliticalLandscape.POLITICAL_LANDSCAPE.POLITICAL_LANDSCAPE_ID, value);
    }

    /**
     * Fetch records that have <code>POLITICAL_LANDSCAPE_NAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.PoliticalLandscape> fetchByPoliticalLandscapeName(String... values) {
        return fetch(PoliticalLandscape.POLITICAL_LANDSCAPE.POLITICAL_LANDSCAPE_NAME, values);
    }
}
