/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.QualityApply;
import top.zbeboy.dms.domain.dms.tables.records.QualityApplyRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class QualityApplyDao extends DAOImpl<QualityApplyRecord, top.zbeboy.dms.domain.dms.tables.pojos.QualityApply, String> {

    /**
     * Create a new QualityApplyDao without any configuration
     */
    public QualityApplyDao() {
        super(QualityApply.QUALITY_APPLY, top.zbeboy.dms.domain.dms.tables.pojos.QualityApply.class);
    }

    /**
     * Create a new QualityApplyDao with an attached configuration
     */
    @Autowired
    public QualityApplyDao(Configuration configuration) {
        super(QualityApply.QUALITY_APPLY, top.zbeboy.dms.domain.dms.tables.pojos.QualityApply.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.dms.domain.dms.tables.pojos.QualityApply object) {
        return object.getQualityApplyId();
    }

    /**
     * Fetch records that have <code>QUALITY_APPLY_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.QualityApply> fetchByQualityApplyId(String... values) {
        return fetch(QualityApply.QUALITY_APPLY.QUALITY_APPLY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>QUALITY_APPLY_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.QualityApply fetchOneByQualityApplyId(String value) {
        return fetchOne(QualityApply.QUALITY_APPLY.QUALITY_APPLY_ID, value);
    }

    /**
     * Fetch records that have <code>STUDENT_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.QualityApply> fetchByStudentId(Integer... values) {
        return fetch(QualityApply.QUALITY_APPLY.STUDENT_ID, values);
    }

    /**
     * Fetch records that have <code>APPLY_CONTENT IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.QualityApply> fetchByApplyContent(String... values) {
        return fetch(QualityApply.QUALITY_APPLY.APPLY_CONTENT, values);
    }

    /**
     * Fetch records that have <code>APPLY_STATE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.QualityApply> fetchByApplyState(Integer... values) {
        return fetch(QualityApply.QUALITY_APPLY.APPLY_STATE, values);
    }

    /**
     * Fetch records that have <code>APPLY_DATE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.QualityApply> fetchByApplyDate(Timestamp... values) {
        return fetch(QualityApply.QUALITY_APPLY.APPLY_DATE, values);
    }
}
