/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.Science;
import top.zbeboy.dms.domain.dms.tables.records.ScienceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ScienceDao extends DAOImpl<ScienceRecord, top.zbeboy.dms.domain.dms.tables.pojos.Science, Integer> {

    /**
     * Create a new ScienceDao without any configuration
     */
    public ScienceDao() {
        super(Science.SCIENCE, top.zbeboy.dms.domain.dms.tables.pojos.Science.class);
    }

    /**
     * Create a new ScienceDao with an attached configuration
     */
    @Autowired
    public ScienceDao(Configuration configuration) {
        super(Science.SCIENCE, top.zbeboy.dms.domain.dms.tables.pojos.Science.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(top.zbeboy.dms.domain.dms.tables.pojos.Science object) {
        return object.getScienceId();
    }

    /**
     * Fetch records that have <code>SCIENCE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Science> fetchByScienceId(Integer... values) {
        return fetch(Science.SCIENCE.SCIENCE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>SCIENCE_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.Science fetchOneByScienceId(Integer value) {
        return fetchOne(Science.SCIENCE.SCIENCE_ID, value);
    }

    /**
     * Fetch records that have <code>SCIENCE_NAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Science> fetchByScienceName(String... values) {
        return fetch(Science.SCIENCE.SCIENCE_NAME, values);
    }

    /**
     * Fetch records that have <code>DEPARTMENT_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Science> fetchByDepartmentId(Integer... values) {
        return fetch(Science.SCIENCE.DEPARTMENT_ID, values);
    }
}
