/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.Student;
import top.zbeboy.dms.domain.dms.tables.records.StudentRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class StudentDao extends DAOImpl<StudentRecord, top.zbeboy.dms.domain.dms.tables.pojos.Student, Integer> {

    /**
     * Create a new StudentDao without any configuration
     */
    public StudentDao() {
        super(Student.STUDENT, top.zbeboy.dms.domain.dms.tables.pojos.Student.class);
    }

    /**
     * Create a new StudentDao with an attached configuration
     */
    @Autowired
    public StudentDao(Configuration configuration) {
        super(Student.STUDENT, top.zbeboy.dms.domain.dms.tables.pojos.Student.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(top.zbeboy.dms.domain.dms.tables.pojos.Student object) {
        return object.getStudentId();
    }

    /**
     * Fetch records that have <code>STUDENT_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByStudentId(Integer... values) {
        return fetch(Student.STUDENT.STUDENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>STUDENT_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.Student fetchOneByStudentId(Integer value) {
        return fetchOne(Student.STUDENT.STUDENT_ID, value);
    }

    /**
     * Fetch records that have <code>STUDENT_NUMBER IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByStudentNumber(String... values) {
        return fetch(Student.STUDENT.STUDENT_NUMBER, values);
    }

    /**
     * Fetch a unique record that has <code>STUDENT_NUMBER = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.Student fetchOneByStudentNumber(String value) {
        return fetchOne(Student.STUDENT.STUDENT_NUMBER, value);
    }

    /**
     * Fetch records that have <code>BIRTHDAY IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByBirthday(Date... values) {
        return fetch(Student.STUDENT.BIRTHDAY, values);
    }

    /**
     * Fetch records that have <code>SEX IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchBySex(String... values) {
        return fetch(Student.STUDENT.SEX, values);
    }

    /**
     * Fetch records that have <code>FAMILY_RESIDENCE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByFamilyResidence(String... values) {
        return fetch(Student.STUDENT.FAMILY_RESIDENCE, values);
    }

    /**
     * Fetch records that have <code>POLITICAL_LANDSCAPE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByPoliticalLandscapeId(Integer... values) {
        return fetch(Student.STUDENT.POLITICAL_LANDSCAPE_ID, values);
    }

    /**
     * Fetch records that have <code>NATION_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByNationId(Integer... values) {
        return fetch(Student.STUDENT.NATION_ID, values);
    }

    /**
     * Fetch records that have <code>DORMITORY_NUMBER IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByDormitoryNumber(String... values) {
        return fetch(Student.STUDENT.DORMITORY_NUMBER, values);
    }

    /**
     * Fetch records that have <code>PARENT_NAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByParentName(String... values) {
        return fetch(Student.STUDENT.PARENT_NAME, values);
    }

    /**
     * Fetch records that have <code>PARENT_CONTACT_PHONE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByParentContactPhone(String... values) {
        return fetch(Student.STUDENT.PARENT_CONTACT_PHONE, values);
    }

    /**
     * Fetch records that have <code>PLACE_ORIGIN IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByPlaceOrigin(String... values) {
        return fetch(Student.STUDENT.PLACE_ORIGIN, values);
    }

    /**
     * Fetch records that have <code>ORGANIZE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByOrganizeId(Integer... values) {
        return fetch(Student.STUDENT.ORGANIZE_ID, values);
    }

    /**
     * Fetch records that have <code>USERNAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Student> fetchByUsername(String... values) {
        return fetch(Student.STUDENT.USERNAME, values);
    }
}
