/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.SystemOperatorLog;
import top.zbeboy.dms.domain.dms.tables.records.SystemOperatorLogRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SystemOperatorLogDao extends DAOImpl<SystemOperatorLogRecord, top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog, String> {

    /**
     * Create a new SystemOperatorLogDao without any configuration
     */
    public SystemOperatorLogDao() {
        super(SystemOperatorLog.SYSTEM_OPERATOR_LOG, top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog.class);
    }

    /**
     * Create a new SystemOperatorLogDao with an attached configuration
     */
    @Autowired
    public SystemOperatorLogDao(Configuration configuration) {
        super(SystemOperatorLog.SYSTEM_OPERATOR_LOG, top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog object) {
        return object.getLogId();
    }

    /**
     * Fetch records that have <code>LOG_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog> fetchByLogId(String... values) {
        return fetch(SystemOperatorLog.SYSTEM_OPERATOR_LOG.LOG_ID, values);
    }

    /**
     * Fetch a unique record that has <code>LOG_ID = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog fetchOneByLogId(String value) {
        return fetchOne(SystemOperatorLog.SYSTEM_OPERATOR_LOG.LOG_ID, value);
    }

    /**
     * Fetch records that have <code>BEHAVIOR IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog> fetchByBehavior(String... values) {
        return fetch(SystemOperatorLog.SYSTEM_OPERATOR_LOG.BEHAVIOR, values);
    }

    /**
     * Fetch records that have <code>OPERATING_TIME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog> fetchByOperatingTime(Timestamp... values) {
        return fetch(SystemOperatorLog.SYSTEM_OPERATOR_LOG.OPERATING_TIME, values);
    }

    /**
     * Fetch records that have <code>USERNAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog> fetchByUsername(String... values) {
        return fetch(SystemOperatorLog.SYSTEM_OPERATOR_LOG.USERNAME, values);
    }

    /**
     * Fetch records that have <code>IP_ADDRESS IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.SystemOperatorLog> fetchByIpAddress(String... values) {
        return fetch(SystemOperatorLog.SYSTEM_OPERATOR_LOG.IP_ADDRESS, values);
    }
}
