/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.SystemConfigure;
import top.zbeboy.dms.domain.dms.tables.records.SystemConfigureRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class SystemConfigureDao extends DAOImpl<SystemConfigureRecord, top.zbeboy.dms.domain.dms.tables.pojos.SystemConfigure, String> {

    /**
     * Create a new SystemConfigureDao without any configuration
     */
    public SystemConfigureDao() {
        super(SystemConfigure.SYSTEM_CONFIGURE, top.zbeboy.dms.domain.dms.tables.pojos.SystemConfigure.class);
    }

    /**
     * Create a new SystemConfigureDao with an attached configuration
     */
    @Autowired
    public SystemConfigureDao(Configuration configuration) {
        super(SystemConfigure.SYSTEM_CONFIGURE, top.zbeboy.dms.domain.dms.tables.pojos.SystemConfigure.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.dms.domain.dms.tables.pojos.SystemConfigure object) {
        return object.getDataKey();
    }

    /**
     * Fetch records that have <code>DATA_KEY IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.SystemConfigure> fetchByDataKey(String... values) {
        return fetch(SystemConfigure.SYSTEM_CONFIGURE.DATA_KEY, values);
    }

    /**
     * Fetch a unique record that has <code>DATA_KEY = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.SystemConfigure fetchOneByDataKey(String value) {
        return fetchOne(SystemConfigure.SYSTEM_CONFIGURE.DATA_KEY, value);
    }

    /**
     * Fetch records that have <code>DATA_VALUE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.SystemConfigure> fetchByDataValue(String... values) {
        return fetch(SystemConfigure.SYSTEM_CONFIGURE.DATA_VALUE, values);
    }
}
