/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import top.zbeboy.dms.domain.dms.tables.Users;
import top.zbeboy.dms.domain.dms.tables.records.UsersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UsersDao extends DAOImpl<UsersRecord, top.zbeboy.dms.domain.dms.tables.pojos.Users, String> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, top.zbeboy.dms.domain.dms.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    @Autowired
    public UsersDao(Configuration configuration) {
        super(Users.USERS, top.zbeboy.dms.domain.dms.tables.pojos.Users.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(top.zbeboy.dms.domain.dms.tables.pojos.Users object) {
        return object.getUsername();
    }

    /**
     * Fetch records that have <code>USERNAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByUsername(String... values) {
        return fetch(Users.USERS.USERNAME, values);
    }

    /**
     * Fetch a unique record that has <code>USERNAME = value</code>
     */
    public top.zbeboy.dms.domain.dms.tables.pojos.Users fetchOneByUsername(String value) {
        return fetchOne(Users.USERS.USERNAME, value);
    }

    /**
     * Fetch records that have <code>PASSWORD IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByPassword(String... values) {
        return fetch(Users.USERS.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>ENABLED IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByEnabled(Boolean... values) {
        return fetch(Users.USERS.ENABLED, values);
    }

    /**
     * Fetch records that have <code>ACCOUNT_NON_EXPIRED IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByAccountNonExpired(Boolean... values) {
        return fetch(Users.USERS.ACCOUNT_NON_EXPIRED, values);
    }

    /**
     * Fetch records that have <code>CREDENTIALS_NON_EXPIRED IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByCredentialsNonExpired(Boolean... values) {
        return fetch(Users.USERS.CREDENTIALS_NON_EXPIRED, values);
    }

    /**
     * Fetch records that have <code>ACCOUNT_NON_LOCKED IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByAccountNonLocked(Boolean... values) {
        return fetch(Users.USERS.ACCOUNT_NON_LOCKED, values);
    }

    /**
     * Fetch records that have <code>AGREE_PROTOCOL IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByAgreeProtocol(Boolean... values) {
        return fetch(Users.USERS.AGREE_PROTOCOL, values);
    }

    /**
     * Fetch records that have <code>USERS_TYPE_ID IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByUsersTypeId(Integer... values) {
        return fetch(Users.USERS.USERS_TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>REAL_NAME IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByRealName(String... values) {
        return fetch(Users.USERS.REAL_NAME, values);
    }

    /**
     * Fetch records that have <code>AVATAR IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByAvatar(String... values) {
        return fetch(Users.USERS.AVATAR, values);
    }

    /**
     * Fetch records that have <code>JOIN_DATE IN (values)</code>
     */
    public List<top.zbeboy.dms.domain.dms.tables.pojos.Users> fetchByJoinDate(Date... values) {
        return fetch(Users.USERS.JOIN_DATE, values);
    }
}
