/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.Evaluate;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EvaluateRecord extends UpdatableRecordImpl<EvaluateRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1392295499;

    /**
     * Setter for <code>DMS.EVALUATE.EVALUATE_ID</code>.
     */
    public void setEvaluateId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.EVALUATE.EVALUATE_ID</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getEvaluateId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DMS.EVALUATE.EVALUATE_CONTENT</code>.
     */
    public void setEvaluateContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.EVALUATE.EVALUATE_CONTENT</code>.
     */
    @Size(max = 200)
    public String getEvaluateContent() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Evaluate.EVALUATE.EVALUATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Evaluate.EVALUATE.EVALUATE_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getEvaluateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEvaluateContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getEvaluateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEvaluateContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluateRecord value1(String value) {
        setEvaluateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluateRecord value2(String value) {
        setEvaluateContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvaluateRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EvaluateRecord
     */
    public EvaluateRecord() {
        super(Evaluate.EVALUATE);
    }

    /**
     * Create a detached, initialised EvaluateRecord
     */
    public EvaluateRecord(String evaluateId, String evaluateContent) {
        super(Evaluate.EVALUATE);

        set(0, evaluateId);
        set(1, evaluateContent);
    }
}
