/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.Grade;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GradeRecord extends UpdatableRecordImpl<GradeRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -671129013;

    /**
     * Setter for <code>DMS.GRADE.GRADE_ID</code>.
     */
    public void setGradeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.GRADE.GRADE_ID</code>.
     */
    public Integer getGradeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DMS.GRADE.GRADE</code>.
     */
    public void setGrade(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.GRADE.GRADE</code>.
     */
    @Size(max = 5)
    public String getGrade() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DMS.GRADE.SCIENCE_ID</code>.
     */
    public void setScienceId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.GRADE.SCIENCE_ID</code>.
     */
    @NotNull
    public Integer getScienceId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Grade.GRADE.GRADE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Grade.GRADE.GRADE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Grade.GRADE.SCIENCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGradeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getScienceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGradeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getScienceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value1(Integer value) {
        setGradeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value2(String value) {
        setGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord value3(Integer value) {
        setScienceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GradeRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GradeRecord
     */
    public GradeRecord() {
        super(Grade.GRADE);
    }

    /**
     * Create a detached, initialised GradeRecord
     */
    public GradeRecord(Integer gradeId, String grade, Integer scienceId) {
        super(Grade.GRADE);

        set(0, gradeId);
        set(1, grade);
        set(2, scienceId);
    }
}
