/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.Organize;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizeRecord extends UpdatableRecordImpl<OrganizeRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1130023194;

    /**
     * Setter for <code>DMS.ORGANIZE.ORGANIZE_ID</code>.
     */
    public void setOrganizeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.ORGANIZE.ORGANIZE_ID</code>.
     */
    public Integer getOrganizeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DMS.ORGANIZE.ORGANIZE_NAME</code>.
     */
    public void setOrganizeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.ORGANIZE.ORGANIZE_NAME</code>.
     */
    @NotNull
    @Size(max = 200)
    public String getOrganizeName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DMS.ORGANIZE.GRADE_ID</code>.
     */
    public void setGradeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.ORGANIZE.GRADE_ID</code>.
     */
    @NotNull
    public Integer getGradeId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Organize.ORGANIZE.ORGANIZE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Organize.ORGANIZE.ORGANIZE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Organize.ORGANIZE.GRADE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOrganizeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOrganizeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGradeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrganizeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrganizeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGradeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizeRecord value1(Integer value) {
        setOrganizeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizeRecord value2(String value) {
        setOrganizeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizeRecord value3(Integer value) {
        setGradeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizeRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizeRecord
     */
    public OrganizeRecord() {
        super(Organize.ORGANIZE);
    }

    /**
     * Create a detached, initialised OrganizeRecord
     */
    public OrganizeRecord(Integer organizeId, String organizeName, Integer gradeId) {
        super(Organize.ORGANIZE);

        set(0, organizeId);
        set(1, organizeName);
        set(2, gradeId);
    }
}
