/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.QualityRelease;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QualityReleaseRecord extends UpdatableRecordImpl<QualityReleaseRecord> implements Record6<String, String, String, Integer, Timestamp, String> {

    private static final long serialVersionUID = -1086292873;

    /**
     * Setter for <code>DMS.QUALITY_RELEASE.QUALITY_RELEASE_ID</code>.
     */
    public void setQualityReleaseId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.QUALITY_RELEASE.QUALITY_RELEASE_ID</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getQualityReleaseId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>DMS.QUALITY_RELEASE.RELEASE_TITLE</code>.
     */
    public void setReleaseTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.QUALITY_RELEASE.RELEASE_TITLE</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getReleaseTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DMS.QUALITY_RELEASE.YEAR</code>.
     */
    public void setYear(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.QUALITY_RELEASE.YEAR</code>.
     */
    @NotNull
    @Size(max = 5)
    public String getYear() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DMS.QUALITY_RELEASE.TERM</code>.
     */
    public void setTerm(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DMS.QUALITY_RELEASE.TERM</code>.
     */
    @NotNull
    public Integer getTerm() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DMS.QUALITY_RELEASE.RELEASE_DATE</code>.
     */
    public void setReleaseDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>DMS.QUALITY_RELEASE.RELEASE_DATE</code>.
     */
    @NotNull
    public Timestamp getReleaseDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>DMS.QUALITY_RELEASE.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DMS.QUALITY_RELEASE.USERNAME</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Integer, Timestamp, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, Integer, Timestamp, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return QualityRelease.QUALITY_RELEASE.QUALITY_RELEASE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QualityRelease.QUALITY_RELEASE.RELEASE_TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return QualityRelease.QUALITY_RELEASE.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return QualityRelease.QUALITY_RELEASE.TERM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return QualityRelease.QUALITY_RELEASE.RELEASE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return QualityRelease.QUALITY_RELEASE.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getQualityReleaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getReleaseTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getTerm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getReleaseDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getQualityReleaseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getReleaseTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTerm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getReleaseDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualityReleaseRecord value1(String value) {
        setQualityReleaseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualityReleaseRecord value2(String value) {
        setReleaseTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualityReleaseRecord value3(String value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualityReleaseRecord value4(Integer value) {
        setTerm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualityReleaseRecord value5(Timestamp value) {
        setReleaseDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualityReleaseRecord value6(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QualityReleaseRecord values(String value1, String value2, String value3, Integer value4, Timestamp value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QualityReleaseRecord
     */
    public QualityReleaseRecord() {
        super(QualityRelease.QUALITY_RELEASE);
    }

    /**
     * Create a detached, initialised QualityReleaseRecord
     */
    public QualityReleaseRecord(String qualityReleaseId, String releaseTitle, String year, Integer term, Timestamp releaseDate, String username) {
        super(QualityRelease.QUALITY_RELEASE);

        set(0, qualityReleaseId);
        set(1, releaseTitle);
        set(2, year);
        set(3, term);
        set(4, releaseDate);
        set(5, username);
    }
}
