/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.School;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchoolRecord extends UpdatableRecordImpl<SchoolRecord> implements Record3<Integer, String, Boolean> {

    private static final long serialVersionUID = 851288790;

    /**
     * Setter for <code>DMS.SCHOOL.SCHOOL_ID</code>.
     */
    public void setSchoolId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.SCHOOL.SCHOOL_ID</code>.
     */
    public Integer getSchoolId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DMS.SCHOOL.SCHOOL_NAME</code>.
     */
    public void setSchoolName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.SCHOOL.SCHOOL_NAME</code>.
     */
    @NotNull
    @Size(max = 200)
    public String getSchoolName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DMS.SCHOOL.SCHOOL_IS_DEL</code>.
     */
    public void setSchoolIsDel(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.SCHOOL.SCHOOL_IS_DEL</code>.
     */
    public Boolean getSchoolIsDel() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Boolean> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Boolean> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return School.SCHOOL.SCHOOL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return School.SCHOOL.SCHOOL_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return School.SCHOOL.SCHOOL_IS_DEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSchoolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSchoolName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component3() {
        return getSchoolIsDel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSchoolId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSchoolName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getSchoolIsDel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value1(Integer value) {
        setSchoolId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value2(String value) {
        setSchoolName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord value3(Boolean value) {
        setSchoolIsDel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SchoolRecord values(Integer value1, String value2, Boolean value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchoolRecord
     */
    public SchoolRecord() {
        super(School.SCHOOL);
    }

    /**
     * Create a detached, initialised SchoolRecord
     */
    public SchoolRecord(Integer schoolId, String schoolName, Boolean schoolIsDel) {
        super(School.SCHOOL);

        set(0, schoolId);
        set(1, schoolName);
        set(2, schoolIsDel);
    }
}
