/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.Science;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScienceRecord extends UpdatableRecordImpl<ScienceRecord> implements Record4<Integer, String, Integer, Boolean> {

    private static final long serialVersionUID = -837323506;

    /**
     * Setter for <code>DMS.SCIENCE.SCIENCE_ID</code>.
     */
    public void setScienceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.SCIENCE.SCIENCE_ID</code>.
     */
    public Integer getScienceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DMS.SCIENCE.SCIENCE_NAME</code>.
     */
    public void setScienceName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.SCIENCE.SCIENCE_NAME</code>.
     */
    @NotNull
    @Size(max = 200)
    public String getScienceName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DMS.SCIENCE.DEPARTMENT_ID</code>.
     */
    public void setDepartmentId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.SCIENCE.DEPARTMENT_ID</code>.
     */
    @NotNull
    public Integer getDepartmentId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>DMS.SCIENCE.SCIENCE_IS_DEL</code>.
     */
    public void setScienceIsDel(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>DMS.SCIENCE.SCIENCE_IS_DEL</code>.
     */
    public Boolean getScienceIsDel() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Boolean> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Boolean> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Science.SCIENCE.SCIENCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Science.SCIENCE.SCIENCE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Science.SCIENCE.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Science.SCIENCE.SCIENCE_IS_DEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getScienceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getScienceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getScienceIsDel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getScienceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getScienceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getScienceIsDel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScienceRecord value1(Integer value) {
        setScienceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScienceRecord value2(String value) {
        setScienceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScienceRecord value3(Integer value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScienceRecord value4(Boolean value) {
        setScienceIsDel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ScienceRecord values(Integer value1, String value2, Integer value3, Boolean value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScienceRecord
     */
    public ScienceRecord() {
        super(Science.SCIENCE);
    }

    /**
     * Create a detached, initialised ScienceRecord
     */
    public ScienceRecord(Integer scienceId, String scienceName, Integer departmentId, Boolean scienceIsDel) {
        super(Science.SCIENCE);

        set(0, scienceId);
        set(1, scienceName);
        set(2, departmentId);
        set(3, scienceIsDel);
    }
}
