/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.Staff;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffRecord extends UpdatableRecordImpl<StaffRecord> implements Record6<Integer, String, String, Integer, Integer, String> {

    private static final long serialVersionUID = -188725294;

    /**
     * Setter for <code>DMS.STAFF.STAFF_ID</code>.
     */
    public void setStaffId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.STAFF.STAFF_ID</code>.
     */
    public Integer getStaffId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DMS.STAFF.STAFF_NUMBER</code>.
     */
    public void setStaffNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.STAFF.STAFF_NUMBER</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getStaffNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DMS.STAFF.SEX</code>.
     */
    public void setSex(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.STAFF.SEX</code>.
     */
    @Size(max = 2)
    public String getSex() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DMS.STAFF.POLITICAL_LANDSCAPE_ID</code>.
     */
    public void setPoliticalLandscapeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DMS.STAFF.POLITICAL_LANDSCAPE_ID</code>.
     */
    public Integer getPoliticalLandscapeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DMS.STAFF.DEPARTMENT_ID</code>.
     */
    public void setDepartmentId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>DMS.STAFF.DEPARTMENT_ID</code>.
     */
    @NotNull
    public Integer getDepartmentId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>DMS.STAFF.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>DMS.STAFF.USERNAME</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Staff.STAFF.STAFF_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Staff.STAFF.STAFF_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Staff.STAFF.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Staff.STAFF.POLITICAL_LANDSCAPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Staff.STAFF.DEPARTMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Staff.STAFF.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStaffId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStaffNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPoliticalLandscapeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStaffId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStaffNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPoliticalLandscapeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDepartmentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value1(Integer value) {
        setStaffId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value2(String value) {
        setStaffNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value3(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value4(Integer value) {
        setPoliticalLandscapeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value5(Integer value) {
        setDepartmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value6(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffRecord
     */
    public StaffRecord() {
        super(Staff.STAFF);
    }

    /**
     * Create a detached, initialised StaffRecord
     */
    public StaffRecord(Integer staffId, String staffNumber, String sex, Integer politicalLandscapeId, Integer departmentId, String username) {
        super(Staff.STAFF);

        set(0, staffId);
        set(1, staffNumber);
        set(2, sex);
        set(3, politicalLandscapeId);
        set(4, departmentId);
        set(5, username);
    }
}
