/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.Student;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record7<Integer, String, String, Integer, String, Integer, String> {

    private static final long serialVersionUID = -368767918;

    /**
     * Setter for <code>DMS.STUDENT.STUDENT_ID</code>.
     */
    public void setStudentId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.STUDENT.STUDENT_ID</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DMS.STUDENT.STUDENT_NUMBER</code>.
     */
    public void setStudentNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.STUDENT.STUDENT_NUMBER</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getStudentNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DMS.STUDENT.SEX</code>.
     */
    public void setSex(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.STUDENT.SEX</code>.
     */
    @Size(max = 2)
    public String getSex() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DMS.STUDENT.POLITICAL_LANDSCAPE_ID</code>.
     */
    public void setPoliticalLandscapeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DMS.STUDENT.POLITICAL_LANDSCAPE_ID</code>.
     */
    public Integer getPoliticalLandscapeId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DMS.STUDENT.PLACE_ORIGIN</code>.
     */
    public void setPlaceOrigin(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DMS.STUDENT.PLACE_ORIGIN</code>.
     */
    @Size(max = 200)
    public String getPlaceOrigin() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DMS.STUDENT.ORGANIZE_ID</code>.
     */
    public void setOrganizeId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>DMS.STUDENT.ORGANIZE_ID</code>.
     */
    @NotNull
    public Integer getOrganizeId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>DMS.STUDENT.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>DMS.STUDENT.USERNAME</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getUsername() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer, String, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Student.STUDENT.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Student.STUDENT.STUDENT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Student.STUDENT.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Student.STUDENT.POLITICAL_LANDSCAPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Student.STUDENT.PLACE_ORIGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Student.STUDENT.ORGANIZE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Student.STUDENT.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStudentNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPoliticalLandscapeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPlaceOrigin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getOrganizeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStudentNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPoliticalLandscapeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPlaceOrigin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getOrganizeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value1(Integer value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value2(String value) {
        setStudentNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value3(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value4(Integer value) {
        setPoliticalLandscapeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value5(String value) {
        setPlaceOrigin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value6(Integer value) {
        setOrganizeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value7(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer studentId, String studentNumber, String sex, Integer politicalLandscapeId, String placeOrigin, Integer organizeId, String username) {
        super(Student.STUDENT);

        set(0, studentId);
        set(1, studentNumber);
        set(2, sex);
        set(3, politicalLandscapeId);
        set(4, placeOrigin);
        set(5, organizeId);
        set(6, username);
    }
}
