/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.Wining;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WiningRecord extends UpdatableRecordImpl<WiningRecord> implements Record6<Integer, String, String, Integer, String, Double> {

    private static final long serialVersionUID = 2020441013;

    /**
     * Setter for <code>DMS.WINING.WINING_ID</code>.
     */
    public void setWiningId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.WINING.WINING_ID</code>.
     */
    public Integer getWiningId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DMS.WINING.STUDENT_NUMBER</code>.
     */
    public void setStudentNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.WINING.STUDENT_NUMBER</code>.
     */
    @NotNull
    @Size(max = 20)
    public String getStudentNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>DMS.WINING.YEAR</code>.
     */
    public void setYear(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.WINING.YEAR</code>.
     */
    @NotNull
    @Size(max = 5)
    public String getYear() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DMS.WINING.TERM</code>.
     */
    public void setTerm(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>DMS.WINING.TERM</code>.
     */
    @NotNull
    public Integer getTerm() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>DMS.WINING.WINING_CONTENT</code>.
     */
    public void setWiningContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>DMS.WINING.WINING_CONTENT</code>.
     */
    @NotNull
    @Size(max = 500)
    public String getWiningContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>DMS.WINING.WINING_SCORE</code>.
     */
    public void setWiningScore(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>DMS.WINING.WINING_SCORE</code>.
     */
    public Double getWiningScore() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, String, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, String, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Wining.WINING.WINING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Wining.WINING.STUDENT_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Wining.WINING.YEAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Wining.WINING.TERM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Wining.WINING.WINING_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Wining.WINING.WINING_SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWiningId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStudentNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getTerm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getWiningContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getWiningScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWiningId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStudentNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getYear();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTerm();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getWiningContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getWiningScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value1(Integer value) {
        setWiningId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value2(String value) {
        setStudentNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value3(String value) {
        setYear(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value4(Integer value) {
        setTerm(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value5(String value) {
        setWiningContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value6(Double value) {
        setWiningScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord values(Integer value1, String value2, String value3, Integer value4, String value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WiningRecord
     */
    public WiningRecord() {
        super(Wining.WINING);
    }

    /**
     * Create a detached, initialised WiningRecord
     */
    public WiningRecord(Integer winingId, String studentNumber, String year, Integer term, String winingContent, Double winingScore) {
        super(Wining.WINING);

        set(0, winingId);
        set(1, studentNumber);
        set(2, year);
        set(3, term);
        set(4, winingContent);
        set(5, winingScore);
    }
}
