/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.dms.domain.dms.tables.records;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import top.zbeboy.dms.domain.dms.tables.Wining;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WiningRecord extends UpdatableRecordImpl<WiningRecord> implements Record4<Integer, Integer, String, Double> {

    private static final long serialVersionUID = 68862468;

    /**
     * Setter for <code>DMS.WINING.WINING_ID</code>.
     */
    public void setWiningId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>DMS.WINING.WINING_ID</code>.
     */
    public Integer getWiningId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>DMS.WINING.CREDIT_ID</code>.
     */
    public void setCreditId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>DMS.WINING.CREDIT_ID</code>.
     */
    @NotNull
    public Integer getCreditId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>DMS.WINING.WINING_CONTENT</code>.
     */
    public void setWiningContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>DMS.WINING.WINING_CONTENT</code>.
     */
    @NotNull
    @Size(max = 500)
    public String getWiningContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>DMS.WINING.WINING_SCORE</code>.
     */
    public void setWiningScore(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>DMS.WINING.WINING_SCORE</code>.
     */
    public Double getWiningScore() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Wining.WINING.WINING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Wining.WINING.CREDIT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Wining.WINING.WINING_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Wining.WINING.WINING_SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWiningId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCreditId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWiningContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getWiningScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWiningId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCreditId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWiningContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getWiningScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value1(Integer value) {
        setWiningId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value2(Integer value) {
        setCreditId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value3(String value) {
        setWiningContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord value4(Double value) {
        setWiningScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WiningRecord values(Integer value1, Integer value2, String value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WiningRecord
     */
    public WiningRecord() {
        super(Wining.WINING);
    }

    /**
     * Create a detached, initialised WiningRecord
     */
    public WiningRecord(Integer winingId, Integer creditId, String winingContent, Double winingScore) {
        super(Wining.WINING);

        set(0, winingId);
        set(1, creditId);
        set(2, winingContent);
        set(3, winingScore);
    }
}
